language: php

php:
- 7.0
- 7.1
- nightly

matrix:
 fast_finish: true
 allow_failures:
 - php: nightly

before_install:
- composer global require hirak/prestissimo

install:
- composer self-update
- composer install

script:
- composer run lint
- composer run test
