language: php

php:
- 7.0
- 7.1
- nightly

matrix:
 fast_finish: true
 allow_failures:
 - php: nightly

before_install:
- composer global require hirak/prestissimo

install:
- composer self-update
- composer install

script:
- bin/porn-terminal -p porn.com -m
- bin/porn-terminal -p pornhub.com -m
- bin/porn-terminal -p redtube.com -m
- bin/porn-terminal -p spankwire.com -m
- bin/porn-terminal -p youporn.com -m
- vendor/bin/phpunit